name: Postgres tests

on:
  [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      DB: postgres # conditions the RDBMS to use with test_app
      DB_PASSWORD: password
      DB_USERNAME: user
      DB_HOST: localhost
      ImageOS: ubuntu20

    services:
      postgres:
        image: postgres:12
        env:
          PG_HOST: ${{ env.DB_HOST }}
          POSTGRES_DB: ${{ env.DB }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_PORT: 5432
          POSTGRES_USER: ${{ env.DB_USERNAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      matrix:
        ruby: ['2.7', '3.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13'

      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '92.0.4515.107'

      - name: Check Ruby version
        run: ruby --version

      - name: Run tests
        run: |
          bundle exec rake test_app
          bundle exec rake spec
